### ISSUE TITLE
220 AC to 3.3 VDC adapter for SPI epapers

### ISSUE THREAD

**Issue by martinberlin** [martinberlin/H-spi-adapters#3]
First sample will be focused just on getting the alternate current into estable 3.3V

- [x] Check the Schematics and get it approved by Carlos F.
- [x] Make the smallest possible design but passing all DRCs 

New Tasks added after some feedback in Twitter (Thanks Rico, Larry and others)

- [ ] **1** Add an [optocoupler](https://www.jameco.com/Jameco/workshop/Howitworks/what-is-an-optocoupler-and-how-it-works.html) to know if the lamp is on 
- [ ] **2** Add 2 [WHITE](https://jlcpcb.com/partdetail/Worldsemi-WS2812B_BW/C2761795) Leds (Or RGBW) 

### Tech notes

1. Latch relay has no way to return if it's ON or OFF) This will also enable some smart behavior like not to count consumption if the light is circuit is not closed (Light is broken for example)
2. For this to happen, we should update the 220AC converter to output 5V instead of 3.3V since otherwise the voltage will be too low for the 2812's (At least in datasheet min. Volts are 3.7 V and it's a known fact that Blue and White need more voltage than the others)

Important and to be considered: With the [ESP32C3](https://www.espressif.com/sites/default/files/documentation/esp32-c3-wroom-02_datasheet_en.pdf) small MCU we use there are only 2 GPIOS left. Adding this two we don't any more available which kind of limits possibilities if you would like to control a second thing in the same epaper UX (2nd latch or simple relay)

**Comment by martinberlin** [comment]
Done. Both PCBs are working but will leave open until last release is for sale

**Comment by Leone25** [comment]
Serious question, shouldn't there be no ground near the switch input? The ground plane under the relay input are kind of messing up the galvanic isolation ...
current: 
![image](https://user-images.githubusercontent.com/39310565/215701845-c1bca8f1-6e69-45f9-a6d6-88a409a15ea4.png)
to something like:
![image](https://user-images.githubusercontent.com/39310565/215703539-2a94652d-e0c0-4914-9aa0-fdcbbcb1599d.png)
Also since there is the space it might be a good idea to increase the trace size of the switched ac side? I know it is limited by the relay anyway but less resistance is better.

**Comment by martinberlin** [comment]
Sure that is a great catch. GND pane there can be dangerous and it's not really needed at all.
The traces are 1 mm. You think 1.5 or 2 mm would be better, then we can update it, no problem.

**Comment by martinberlin** [comment]
Point 1 might be implemented in next Release. Leds for the moment not. 
A more elegant solution would be to have a front-light LED layer over the epaper.
